version: '3'
services:
  web:
    build: .
    ports:
     - "8080:3000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  user-service:
    image: "webdevtoolsandtech/user-service"
    environment:
      REDIS_ADDRESS: "redis:6379"
    ports:
      - "3002:80"
  currency-frontend:
    image: "webdevtoolsandtech/currency-frontend"
    ports:
      - "5000:80"
  currency-backend:
    image: "webdevtoolsandtech/currency-backend"
    ports:
      - "80:80"
    environment:
      REDIS_ADDRESS: "redis:6379"
      SESSION_SECRET: "blabla"
      USER_SERVICE_ADDRESS: "user-service:80"
      FRONTEND_ADDRESS: "currency-frontend:80"
      CALCULATOR_ADDRESS: "web:3000"